<?php
class booking_tour
{
    public $id,$code_booking,$tour_id,$name_tour,$name_customer,$language,$phone,$email,$address,$departure_day,$num_nguoi_lon,$num_tre_em_m1,$num_tre_em_m2,$num_tre_em_m3,$price,$price_2,$price_3,$price_4,$total_price,$request,$status,$created;
    public function booking_tour($data=array())
    {
        $this->id=isset($data['id'])?$data['id']:'';
        $this->code_booking=isset($data['code_booking'])?$data['code_booking']:'';
        $this->tour_id=isset($data['tour_id'])?$data['tour_id']:'';
        $this->name_tour=isset($data['name_tour'])?$data['name_tour']:'';
        $this->name_customer=isset($data['name_customer'])?$data['name_customer']:'';
        $this->language=isset($data['language'])?$data['language']:'';
        $this->phone=isset($data['phone'])?$data['phone']:'';
        $this->email=isset($data['email'])?$data['email']:'';
        $this->address=isset($data['address'])?$data['address']:'';
        $this->departure_day=isset($data['departure_day'])?$data['departure_day']:'';
        $this->num_nguoi_lon=isset($data['num_nguoi_lon'])?$data['num_nguoi_lon']:'';
        $this->num_tre_em_m1=isset($data['num_tre_em_m1'])?$data['num_tre_em_m1']:'';
        $this->num_tre_em_m2=isset($data['num_tre_em_m2'])?$data['num_tre_em_m2']:'';
        $this->num_tre_em_m3=isset($data['num_tre_em_m3'])?$data['num_tre_em_m3']:'';
        $this->price=isset($data['price'])?$data['price']:'';
        $this->price_2=isset($data['price_2'])?$data['price_2']:'';
        $this->price_3=isset($data['price_3'])?$data['price_3']:'';
        $this->price_4=isset($data['price_4'])?$data['price_4']:'';
        $this->total_price=isset($data['total_price'])?$data['total_price']:'';
        $this->request=isset($data['request'])?$data['request']:'';
        $this->status=isset($data['status'])?$data['status']:'';
        $this->created=isset($data['created'])?$data['created']:'';
        $this->encode();
    }
    public function encode()
    {
        $this->id=addslashes($this->id);
        $this->code_booking=addslashes($this->code_booking);
        $this->tour_id=addslashes($this->tour_id);
        $this->name_tour=addslashes($this->name_tour);
        $this->name_customer=addslashes($this->name_customer);
        $this->language=addslashes($this->language);
        $this->phone=addslashes($this->phone);
        $this->email=addslashes($this->email);
        $this->address=addslashes($this->address);
        $this->departure_day=addslashes($this->departure_day);
        $this->num_nguoi_lon=addslashes($this->num_nguoi_lon);
        $this->num_tre_em_m1=addslashes($this->num_tre_em_m1);
        $this->num_tre_em_m2=addslashes($this->num_tre_em_m2);
        $this->num_tre_em_m3=addslashes($this->num_tre_em_m3);
        $this->price=addslashes($this->price);
        $this->price_2=addslashes($this->price_2);
        $this->price_3=addslashes($this->price_3);
        $this->price_4=addslashes($this->price_4);
        $this->total_price=addslashes($this->total_price);
        $this->request=addslashes($this->request);
        $this->status=addslashes($this->status);
        $this->created=addslashes($this->created);
    }
    public function decode()
    {
        $this->id=stripslashes($this->id);
        $this->code_booking=stripslashes($this->code_booking);
        $this->tour_id=stripslashes($this->tour_id);
        $this->name_tour=stripslashes($this->name_tour);
        $this->name_customer=stripslashes($this->name_customer);
        $this->language=stripslashes($this->language);
        $this->phone=stripslashes($this->phone);
        $this->email=stripslashes($this->email);
        $this->address=stripslashes($this->address);
        $this->departure_day=stripslashes($this->departure_day);
        $this->num_nguoi_lon=stripslashes($this->num_nguoi_lon);
        $this->num_tre_em_m1=stripslashes($this->num_tre_em_m1);
        $this->num_tre_em_m2=stripslashes($this->num_tre_em_m2);
        $this->num_tre_em_m3=stripslashes($this->num_tre_em_m3);
        $this->price=stripslashes($this->price);
        $this->price_2=stripslashes($this->price_2);
        $this->price_3=stripslashes($this->price_3);
        $this->price_4=stripslashes($this->price_4);
        $this->total_price=stripslashes($this->total_price);
        $this->request=stripslashes($this->request);
        $this->status=stripslashes($this->status);
        $this->created=stripslashes($this->created);
    }
}
