insert into khachsan (danhmuc_id,name,name_url,start,room_type,img,content,title,keyword,description) values ('1','Florenze','florenze','4','','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/1.jpg','<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
','Florenze','Florenze','Florenze');
insert into khachsan (danhmuc_id,name,name_url,start,room_type,img,content,title,keyword,description) values ('1','Toluca','toluca','3','','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/2.jpg','<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
','Toluca','Toluca','Toluca');
insert into khachsan (danhmuc_id,name,name_url,start,room_type,img,content,title,keyword,description) values ('1','Venice','venice','5','','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg','<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
','Venice','Venice','Venice');
insert into khachsan (danhmuc_id,name,name_url,start,room_type,img,content,title,keyword,description) values ('1','Ohio','ohio','4','','','<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
','Ohio','Ohio','Ohio');
insert into khachsan (danhmuc_id,name,name_url,start,room_type,img,content,title,keyword,description) values ('1','Venice','venice','5','','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/5.jpg','<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
','Venice','Venice','Venice');
update khachsan set danhmuc_id='1',name='Ohio',name_url='ohio',start='4',price='200000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Ohio',keyword='Ohio',description='Ohio' where id=4;
update khachsan set danhmuc_id='1',name='Venice',name_url='venice',start='5',price='600000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/5.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=5;
update khachsan set danhmuc_id='1',name='Venice',name_url='venice',start='5',price='500000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=3;
update khachsan set danhmuc_id='1',name='Venice',name_url='venice',start='5',price='1000000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=3;
update khachsan set danhmuc_id='1',name='Toluca',name_url='toluca',start='3',price='600000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/2.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Toluca',keyword='Toluca',description='Toluca' where id=2;
update khachsan set danhmuc_id='1',highlights='1',name='Venice',name_url='venice',start='5',price='600000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/5.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=5;
update khachsan set danhmuc_id='1',highlights='1',name='Ohio',name_url='ohio',start='4',price='200000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Ohio',keyword='Ohio',description='Ohio' where id=4;
update khachsan set danhmuc_id='1',highlights='1',name='Venice',name_url='venice',start='5',price='1000000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=3;
update khachsan set danhmuc_id='1',highlights='1',name='Toluca',name_url='toluca',start='3',price='600000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/2.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Toluca',keyword='Toluca',description='Toluca' where id=2;
update khachsan set danhmuc_id='1',highlights='1',name='Florenze',name_url='florenze',start='4',price='',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/1.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Florenze',keyword='Florenze',description='Florenze' where id=1;
update khachsan set danhmuc_id='1',highlights='1',name='Venice',name_url='venice',start='5',price='600000',room_type='',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/5.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=5;
update khachsan set danhmuc_id='1',highlights='1',name='Florenze',name_url='florenze',start='4',price='',room_type='2,4',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/1.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Florenze',keyword='Florenze',description='Florenze' where id=1;
update khachsan set danhmuc_id='1',highlights='1',name='Toluca',name_url='toluca',start='3',price='600000',room_type='2,3,4',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/2.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Toluca',keyword='Toluca',description='Toluca' where id=2;
update khachsan set danhmuc_id='1',highlights='1',name='Venice',name_url='venice',start='5',price='1000000',room_type='1,3,4',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=3;
update khachsan set danhmuc_id='1',highlights='1',name='Ohio',name_url='ohio',start='4',price='200000',room_type='1,2,3',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Ohio',keyword='Ohio',description='Ohio' where id=4;
update khachsan set danhmuc_id='1',highlights='1',name='Venice',name_url='venice',start='5',price='600000',room_type='1,2',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/5.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=5;
update khachsan set danhmuc_id='1',highlights='1',name='Venice test',name_url='venice-test',start='5',price='600000',room_type='1,2',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/5.jpg',content='<p>
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"box-sizing: border-box; background-color: rgb(250, 250, 250); color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Venice',keyword='Venice',description='Venice' where id=5;
